### 회원가입
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "email": "",
  "password": "",
  "userRole": ""
}

### 로그인
POST http://localhost:8080/auth/signin
Content-Type: application/json

{
  "email": "",
  "password": ""
}