### 특정 todo에 매니저 지정(등록)
POST http://localhost:8080/todos/{{todoId}}/managers
Content-Type: application/json

{
  "managerUserId": 1
}

### 특정 todo 매니저 조회
GET http://localhost:8080/todos/{{todoId}}/managers
Content-Type: application/json

### 특정 todo 매니저 삭제
DELETE http://localhost:8080/todos/{{todoId}}/managers/{{managerId}}