### 특정 사용자(유저) 조회
GET http://localhost:8080/users/{{userId}}

### 비밀번호 변경
PUT http://localhost:8080/users
Content-Type: application/json

{
  "oldPassword": "aaa",
  "newPassword": "AAA"
}

### 역할(role) 변경
PATCH http://localhost:8080/admin/users/{{userId}}
Content-Type: application/json

{
  "role": ""
}